### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by kshitij10496** [icyflame/cutouts#29]
Hey @icyflame 

Recently, I have restarted using Cutouts to store passages from paperbacks - which I find to be absolutely perfect for the usecase.
Also, I maintain a page listing all my favourite quotes on my personal homepage.

Basically, now I have to copy-paste a lot of information to the markdown format from Cutouts.
Moreover, keeping them in sync is getting difficult. 😢
I'm thinking of automating the process of formatting and syncing for me.

Would it be possible to document some API endpoints related to data fetching?
I was wondering if we can easily document the API using Swagger(or any other alternatives).

**Comment by icyflame** [comment]
@kshitij10496 Absolutely! I already have a simple API that allows fetching the cutouts. I think I can work on getting the "public" quotes for a given account. Let me do that and let you know what sort of functions it can support.

**Comment by kshitij10496** [comment]
Awesome! That would be perfect.
Thanks 😄 🎉

**Comment by icyflame** [comment]
@kshitij10496 There is an API for this already:

```sh
https://cutouts.siddharthkannan.in/api/v1/feed/:username
```

This returns a JSON of your first 20 quotes. I haven't yet implemented pagination though, that is still pending.
