### ISSUE TITLE
Search for articles with a particular tag

### ISSUE THREAD

**Issue by icyflame** [icyflame/cutouts#9]
- General search now works, but tag search is required
- The tags that are displayed on the mainpage should be clickable themselves (leading to all articles tagged with that exact tag. Use `contains` instead of `like`)

**Comment by sampatbadhe** [comment]
@icyflame Can we use `acts-as-taggable-on` gem to save tags? 
https://github.com/mbleigh/acts-as-taggable-on

**Comment by icyflame** [comment]
@sampatbadhe I have looked through that Gem, but I think it will be overkill to use that here. I just want to use the ORM queries because they are sufficient for display and look-up. (Which are the only two things I am thinking of doing with tags)

**Comment by icyflame** [comment]
Thanks for the suggestion, in any case! :smile:
